// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFUhk-N_CdQ7w6piGpGn4v72zEuWgAn6c',
    appId: '1:318075785441:web:37c37781c46e386733a7a0',
    messagingSenderId: '318075785441',
    projectId: 'fir-f651c',
    authDomain: 'fir-f651c.firebaseapp.com',
    databaseURL: 'https://fir-f651c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-f651c.appspot.com',
    measurementId: 'G-G2MMGVN0RP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9WjeLbcTK4sBjCr7ix3FQrk5g86MomtE',
    appId: '1:318075785441:android:f1d94dd21955847133a7a0',
    messagingSenderId: '318075785441',
    projectId: 'fir-f651c',
    databaseURL: 'https://fir-f651c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-f651c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDIi01a1FBf8_s-Xair5bzckLpv_pObAA',
    appId: '1:318075785441:ios:dc0051d779879e5133a7a0',
    messagingSenderId: '318075785441',
    projectId: 'fir-f651c',
    databaseURL: 'https://fir-f651c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-f651c.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDIi01a1FBf8_s-Xair5bzckLpv_pObAA',
    appId: '1:318075785441:ios:7ae52b8e251e5f7a33a7a0',
    messagingSenderId: '318075785441',
    projectId: 'fir-f651c',
    databaseURL: 'https://fir-f651c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-f651c.appspot.com',
    iosBundleId: 'com.example.firebaseProject.RunnerTests',
  );
}
